branches:
  only:
    - master

language: android
jdk: oraclejdk7
env:
  global:
  - secure: HFrTJGqM13CLydBxYKVDVzxyxML8ivAdb0Q7WZsqF0Ou+mrin9+uj4tIc6fGo5SJaXRV5pLEXE5aXfzMqhdv80WBafe0n7aQLizlOJG2Z6PhYu8ojY7hjtVnYUtYj62uoP+Vh/YgWiAjPGZ3No3NSNmJ0noJkaFkDP0xyUAs6TE=
  - secure: QbNqQu3xj6erKQIy/r76vIjubmzqdZ8CpILRsb0S1bVuE6ntAFkyQlFUzkGgqiUXpxuXeM/U8yGQJND+S4X+zFvEnLftdkK5x/TpYLruVo+C0pSetn6AHmAeg6yRnoEOsEDbjTAMnlygwPd8T9R2TNt62HtEH/5H1w2FkGkWmrE=

android:
  components:
  - tools
  - platform-tools
  - extra-android-support
  - extra-android-m2repository
  - android-22
  - build-tools-22.0.1
install:
  - ./gradlew dependencies

script:
  - ./gradlew build

after_success:
  - ./gradlew uploadArchives
